- hosts: tag_type_staging
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Setting ip address
      command: docker exec -it laravel bash -c 'sed -ri "s/(\\b[0-9]{1,3}\\.){3}[0-9]{1,3}\\b/3.108.160.3/g" ./tests/acceptance.suite.yml';
    - name: Run acceptance tests
      command: docker exec -it laravel bash -c 'vendor/bin/codecept run';
      register: atesting
    - debug: msg="{{ atesting.stdout }}"
