- hosts: tag_type_production
  become: yes
  remote_user: ec2-user
  name: Upgrade all packages
  tasks:
    - name: Update all
      yum: name=* state=latest
    - name: install docker
      yum: name=docker state=latest
    - name: Start docker service
      systemd:
        state: started
        name: docker
    - name: Add admin user
      user:
        name: admin
        groups: docker
        append: yes
    - name: install python-pip
      yum: name=python-pip state=present
    - name: install docker-py
      pip: name=docker-py
    - name: Delete laravel containers
      docker_container:
        name: laravel
        force_kill: true
        keep_volumes: false
        state: absent
    - name: ECR creds copy
      copy:
        src: /tmp/ecr_password.txt
        dest: /tmp/
        owner: admin
        group: docker
        mode: 777
    - name: ECR login
      shell: cat /tmp/ecr_password.txt | docker login --username AWS --password-stdin 309853523083.dkr.ecr.ap-south-1.amazonaws.com
    - name: Remove image
      docker_image:
        state: absent
        name: 309853523083.dkr.ecr.ap-south-1.amazonaws.com/jenkins-ci 
    - name: Run laravel container
      docker_container:
        name: laravel
        image: 309853523083.dkr.ecr.ap-south-1.amazonaws.com/jenkins-ci 
        state: started
        exposed_ports: "80"
        published_ports: "80:80"
