- hosts: tag_type_production
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Insert ip address
      command: docker exec -it laravel bash -c 'sed -ri "s/(\\b[0-9]{1,3}\\.){3}[0-9]{1,3}\\b/15.206.50.15/g" ./tests/acceptance.suite.yml';
    - name: Run somke tests
      command: docker exec -it laravel bash -c 'vendor/bin/codecept run';
      register: stesting
    - debug: msg="{{ stesting.stdout }}"
